sudo: required
dist: trusty
language: generic
os:
- linux
script:
- make
deploy:
  provider: releases
  api_key:
    secure: DfLcrK84pA2Bcx21jfCruUdw/8EGl4nKe+O1EoNZWrOuj0PGAQ5r508hljxCdc/ME0cE8gXWMzK0LaYGB64EF7D0T+8x0qz2I2ZdO6a0Troswum/lr5XihF7jdXzun5EVOnclykiW9icXXpjJGVAGZi/4s/5GerYuAkvvcJczNfD0TIpCpwaB3g+GBL3DZZB+MsAWvx1ITV9KkB17GdBIm2ptKXtAje6v+RtQZ3/xzw9/OWB7RzG/Yr2MrAu4ynXPws10GfFwdTYH+EjWoDNYax1d/xok4UoPxkxep4wcbwUhXjz8fWvL9R/pLRNkpxvlVEWHAAULsr0UJEjRxV5s+P/0LjEzkzDUzumn0cYYVbZTyKWkU8ZEy3jNet2EhfFoSVeRujSRTYotXsOcs5sU3YWcOI0/YKK1q0CbDML0+VhyY8+PXL5K2KcC5LuZu4D/uyMsqNI4vT2BjPs2vuWwoOMN1JgASQ+8jsODF1HBwxlbCxJ8zZGAYOVYCpRmbx4o90I5NeKTbdUlXOpagHc0XtC57GxlypYzLYgkia1wNstWPw7FDvXQgQV2mewJwI2JkO8+wpM4gFJXx29Tch9tslnYhwXUzsay+x/2HCcs1iUpwxWwqB86YGjqghmIvMTKJrZKVEEEmbdMoMNVgl8hcuLRgdxFqgY3xzQRXuiK+k=
  file: current.zip
  skip_cleanup: true
  on:
    repo: ClocxHD/screencloud-plugin-ftps
notifications:
  slack:
    secure: TnAsr7rzC4p4n5ukTqaOm84wKksaCOEqVUvWWDt01/e6P4ytcAqhiKbldVZl7vTLqy3a5nlexXngNIj77WWVgLKbxLh9j5BXgVTTcFMJyuNkG39uHP7853MousLDKAIdLNc0U6QGmrLHN8AiJQf6k3+7gEwmStFAx3v92qrOr+eXEwwh2GbLrH+lmg8r/R/3m8Y2MGaO4BVNAPfJew8GosQwsFOyG5SZ8HL4F6K7/DjaiBhATTzZjADMszkyPOQiYo5iz1muKg9KmgOE1bRFsztJinX8DFgkXVvxPo6PjyaDC3uNNCyeOtB2Av3HRdj0jorxAjtzpN+SH56duYB7RVJ4RAuoXpNOexgGvqdJtw2XPHc2mGCDpUxqqmT/Kb+JEFVMyj1kWkhxsgHOUjbSf3pcozxHQpNnUCWuOzgJ5LnrR5Cv+AAmSaVaGXi8GZgLZTWe337Uomi9I5Zf2hPkI8DTkDQeFxSLw5Bhs0+tFjDEbwa/Q3jgnPt8PtnOHnvrPH0LsfkmenO5OrTpEowyMpn+N29qrerZ2ODPzGc61KzrH2Ktda7hRN/1DFn9p4OXUujz5TND5fY5QDkrO61tfdgRlagVpYL+h1DFPgMEB9ztv7zqfaFOdBVqo3Rdi2tQcvtRbyoEMNLR4bij0gCOMcUigLJoD/zZaRHXr0E/Iio=